name = "demo-todo-app"
type = "webpack"
webpack_config = "webpack.config.js"
account_id = "xxxx"
workers_dev = false
zone_id = "xxxx"
route = "xx.macrometa.io/*"
vars = { API_KEY="xxxx", COLLECTION_NAME="todo" }
